<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fish</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*(function|while|if|switch|for)\s.*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*end\s*$</string>
	<key>keyEquivalent</key>
	<string>^~F</string>
	<key>name</key>
	<string>fish</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.fish</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Single quoted string</string>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.fish</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.fish</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\\"|\\\$|\\\\</string>
					<key>name</key>
					<string>constant.character.escape.fish</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.fish</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>single quoted string</string>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.fish</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.fish</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\'|\\</string>
					<key>name</key>
					<string>constant.character.escape.fish</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.fish</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>line comment</string>
			<key>match</key>
			<string>(?&lt;!\$)(#)(?!\{).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.fish</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>control structures requiring an end</string>
			<key>match</key>
			<string>(?&lt;!\.)\b(function|while|if|else|switch|for|in|end)\b(?![?!])</string>
			<key>name</key>
			<string>keyword.control.fish</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.fish</string>
	<key>uuid</key>
	<string>9CA6DB6F-A16F-4836-A058-617C7378775D</string>
</dict>
</plist>
